repos:
- repo: local
  hooks:
  - id: make-pre-commit
    name: Run Makefile pre-commit checks
    entry: make pre-commit
    language: system
    pass_filenames: false # Makefile target doesn't need filenames
    always_run: true      # Run if any files are staged
    stages: [commit]
