[profile.default]
src = 'src'
out = 'out'
libs = ['.deps']
script = 'scripts'
test = 'tests'
solc = "0.8.28"
optimizer = true
optimizer_runs = 200      # High value for optimized deployed contracts
via_ir = false            # Enable intermediate representation compilation for more optimizations
evm_version = "london"    # Use London EVM version for better gas optimizations
metadata_hash = "none"    # Reduces bytecode size
bytecode_hash = "none"    # Further reduces bytecode size
cbor_metadata = false     # Don't include CBOR metadata

[profile.debug]
src = 'src'
out = 'out'
libs = ['.deps']
script = 'scripts'
test = 'tests'
solc = "0.8.28"
optimizer = false
verbosity = 4
