// SPDX-License-Identifier: MIT
pragma solidity ^0.8.29;

/*
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY ⚠️
 *
 * This file is auto-generated by scripts/generate_deployers.py
 * Any manual changes will be overwritten on the next build.
 *
 * To modify this contract:
 * 1. Edit the template: scripts/templates/MainDiamondDeployer.sol.tpl
 * 2. Update configuration: scripts/contracts.json
 * 3. Regenerate: python3 scripts/generate_deployers.py
 */

import {ICreateX} from "@interfaces/ICreateX.sol";
import {IDiamond, IDiamondCut, FacetCut, FacetCutAction} from "@interfaces/IDiamond.sol";
import {BTRTokenDeployer} from "@utils/BTRTokenDeployer.gen.sol";
import {BTRDiamondDeployer} from "@utils/BTRDiamondDeployer.gen.sol";
{{FACET_IMPORTS}}

/*
 * @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 * @@@@@@@@@/         '@@@@/            /@@@/         '@@@@@@@@
 * @@@@@@@@/    /@@@    @@@@@@/    /@@@@@@@/    /@@@    @@@@@@@
 * @@@@@@@/           _@@@@@@/    /@@@@@@@/    /.     _@@@@@@@@
 * @@@@@@/    /@@@    '@@@@@/    /@@@@@@@/    /@@    @@@@@@@@@@
 * @@@@@/            ,@@@@@/    /@@@@@@@/    /@@@,    @@@@@@@@@
 * @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 *
 * @title DiamondDeployer - Generated deployment orchestrator
 * @copyright 2025
 * @notice One-time use deployer that orchestrates all BTR contract deployments
 * @dev Deploys token, diamond, all facets, and cuts them into diamond, then self-destructs
 * @author BTR Team - Generated by scripts/generate_deployers.py
 */

contract DiamondDeployer {
    // Expected deployment addresses
    address public constant DIAMOND_ADDR = {{DIAMOND_ADDRESS}};
    address public constant TOKEN_ADDR = {{TOKEN_ADDRESS}};

    constructor(address admin, address treasury) {
        // Deploy BTR token first
        new BTRTokenDeployer(admin, treasury);

        // Deploy diamond (without facets initially)
        new BTRDiamondDeployer(admin, treasury, new FacetCut[](0));

        // Deploy and cut all facets into the diamond
{{FACET_DEPLOYMENTS}}

        // All deployments complete, self-destruct
        selfdestruct(payable(msg.sender));
    }
}
