// SPDX-License-Identifier: MIT
pragma solidity ^0.8.29;

/*
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY ⚠️
 *
 * This file is auto-generated by scripts/generate_deployers.py
 * Any manual changes will be overwritten on the next build.
 *
 * To modify this contract:
 * 1. Edit the template: scripts/templates/TokenDeployer.sol.tpl
 * 2. Update configuration: scripts/contracts.json
 * 3. Regenerate: python3 scripts/generate_deployers.py
 */

import {ICreateX} from "@interfaces/ICreateX.sol";
import {BTR} from "@/BTR.sol";

/**
 * @title BTRTokenDeployer
 * @notice Self-destructing deployer for BTR token
 * @dev Deploys BTR token via CreateX with constructor args, then self-destructs
 */
contract BTRTokenDeployer {
    ICreateX constant CREATEX = ICreateX(0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed);
    bytes32 constant SALT = {{SALT}};
    address constant EXPECTED_ADDR = {{EXPECTED_ADDRESS}};

    constructor(address admin, address treasury) {
        bytes memory bytecode = abi.encodePacked(
            type(BTR).creationCode,
            abi.encode(admin, treasury)
        );
        address deployed = CREATEX.deployCreate3(SALT, bytecode);
        require(deployed == EXPECTED_ADDR, "BTRToken deployment address mismatch");
        require(deployed != address(0), "BTRToken deployment failed");
        selfdestruct(payable(msg.sender));
    }
}
